### ISSUE TITLE
External Drafts isn't working in production environment.

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-drafts#2]
I checked to make sure everything is deployed and that the addon is present. The weird thing is that the plugin seems to work locally. I'm assuming its something in the prod environment that isn't allowing it to work right?

The entry in question is: https://zaytuna.edu/cp/pages/edit/community-learning/permaculture-design-certificate

![72824829-c931d280-3c2a-11ea-9904-d0ad0c8be5d7](https://user-images.githubusercontent.com/6069653/72826280-65f56f80-3c2d-11ea-8260-a4f7c5813847.png)

**Comment by edalzell** [comment]
@adnankussair I pushed a change to simple, can you test and deploy to zaytuna?

I think the file was getting loaded AFTER all the DOM content was already loaded so the listener wasn't getting triggered.

**Comment by adnankussair** [comment]
@edalzell yes, working on it now.

**Comment by adnankussair** [comment]
@edalzell Just deployed and still having the same issue. No dropdown on draft.

**Comment by edalzell** [comment]
Fix confirmed via Chrome on live site.
